{{- if .Values.nginx.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "artifactory-ha.nginx.fullname" . }}
  labels:
    app: {{ template "artifactory-ha.name" . }}
    chart: {{ template "artifactory-ha.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: {{ .Values.nginx.name }}
  {{- if .Values.nginx.service.labels }}
{{ toYaml .Values.nginx.service.labels | indent 4 }}
  {{- end }}
{{- if .Values.nginx.service.annotations }}
  annotations:
{{ toYaml .Values.nginx.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.nginx.service.type }}
  {{- if and (eq .Values.nginx.service.type "ClusterIP") .Values.nginx.service.clusterIP }}
  clusterIP: {{ .Values.nginx.service.clusterIP }}
  {{- end }}
{{- if eq .Values.nginx.service.type "LoadBalancer" }}
  {{ if .Values.nginx.service.loadBalancerIP -}}
  loadBalancerIP: {{ .Values.nginx.service.loadBalancerIP }}
  {{ end -}}
  {{- if .Values.nginx.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.nginx.service.externalTrafficPolicy }}
  {{- end }}
{{- end }}
{{- if .Values.nginx.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.nginx.service.loadBalancerSourceRanges | indent 4 }}
{{- end }}
  ports:
  {{- if .Values.artifactory.replicator.enabled }}
  - port: {{ .Values.nginx.replicator.externalPort }}
    targetPort: {{ .Values.nginx.replicator.internalPort }}
    protocol: TCP
    name: replicator
  {{- end }}
  {{- if .Values.nginx.http.enabled }}
  - port: {{ .Values.nginx.http.externalPort }}
    targetPort: {{ .Values.nginx.http.internalPort }}
    protocol: TCP
    name: http
  {{- end }}
  {{- if .Values.nginx.https.enabled }}
  - port: {{ .Values.nginx.https.externalPort }}
    targetPort: {{ .Values.nginx.https.internalPort }}
    protocol: TCP
    name: https
  {{- end }}
  selector:
    app: {{ template "artifactory-ha.name" . }}
    component: {{ .Values.nginx.name }}
    release: {{ .Release.Name }}
{{- end }}
